-- Seed data — initial system configs and default questionnaire items

-- System configs
INSERT INTO system_config (key, value, description) VALUES
    ('task_days', '3', '旅行天数'),
    ('task_budget', '1000', '旅行预算(元)'),
    ('target_email', 'experiment@example.com', '收件邮箱'),
    ('destination', '杭州', '目的地'),
    ('target_sample_size', '100', '目标样本量'),
    ('experiment_active', 'true', '实验是否开启'),
    ('block_size', '6', '区组大小')
ON CONFLICT (key) DO NOTHING;

-- Default admin (password: admin123 — bcrypt hash will be generated by app)
-- This is a placeholder; the app's seed_service will create the real admin
INSERT INTO system_config (key, value, description) VALUES
    ('_admin_seeded', 'false', '管理员是否已初始化')
ON CONFLICT (key) DO NOTHING;

-- Questionnaire items (6 constructs, 15 items)
INSERT INTO questionnaire_items (construct, question_text, question_type, scale_level, sort_order, options) VALUES
    -- trust — 感知信任（措辞对 H 组手动工具与 SOA/MOA 组 AI 均适用）
    ('trust', '我认为任务中所获得的旅行信息（如景点、路线建议）是可靠的', 'likert', 5, 1, NULL),
    ('trust', '我信任系统/工具为我生成的行程规划建议', 'likert', 5, 2, NULL),
    ('trust', '我在使用本系统的过程中，感到我的操作与数据是安全、可控的', 'likert', 5, 3, NULL),
    -- autonomy — 感知自主性
    ('autonomy', '我能自主决定如何完成任务，而非被系统主导', 'likert', 5, 4, NULL),
    ('autonomy', '在整个任务过程中，我感到自己对进度有充分的掌控', 'likert', 5, 5, NULL),
    ('autonomy', '我可以根据自己的想法随时调整完成任务的方式', 'likert', 5, 6, NULL),
    -- satisfaction — 满意度
    ('satisfaction', '我对完成旅行规划任务的整体体验感到满意', 'likert', 5, 7, NULL),
    ('satisfaction', '我满意完成任务过程中所获得支持的响应质量', 'likert', 5, 8, NULL),
    -- task_load — 任务负荷 (NASA-TLX)
    ('task_load', '完成旅行规划任务让我感到脑力负荷很大', 'likert', 7, 9, NULL),
    ('task_load', '我需要在多个工具/步骤之间频繁切换，增加了我的负担', 'likert', 7, 10, NULL),
    ('task_load', '整体而言，完成本次任务所需的努力程度很高', 'likert', 7, 11, NULL),
    -- future_use — 未来使用意愿
    ('future_use', '如果未来有类似的任务，我愿意继续使用本系统/工具', 'likert', 5, 12, NULL),
    ('future_use', '我会向他人推荐本系统/工具用于旅行规划', 'likert', 5, 13, NULL),
    -- manipulation_check — 操纵检验
    ('manipulation_check', '在本次任务中，你是否使用了AI助理来协助完成旅行规划？', 'choice', 0, 14, '["是","否","不确定"]'::jsonb),
    ('manipulation_check', '你认为本次任务中为你提供辅助的AI助理数量是？', 'choice', 0, 15, '["0个（纯人工）","1个","多个"]'::jsonb)
ON CONFLICT DO NOTHING;
